sonar.organization=tu-org-sonarcloud
sonar.projectKey=tu-org_exam-craft-extension
sonar.sources=src
sonar.exclusions=node_modules/**,build/**,.plasmo/**,logs/**
sonar.typescript.tsconfigPath=tsconfig.json